---
development:
  cloud_name: <%= ENV["CLOUD_NAME"]%>
  api_key: <%= ENV['CLOUD_KEY']%>
  api_secret: <%= ENV['CLOUD_SECRET']%>
  enhance_image_tag: true
  static_file_support: false
test:
  cloud_name: <%= ENV["CLOUD_NAME"]%>
  api_key: <%= ENV['CLOUD_KEY']%>
  api_secret: <%= ENV['CLOUD_SECRET']%>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: <%= ENV["PROD_CLOUD_NAME"]%>
  api_key: <%= ENV['PROD_CLOUD_KEY']%>
  api_secret: <%= ENV['PROD_CLOUD_SECRET']%>
  enhance_image_tag: true
  static_file_support: true